// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file draft/ydb_keyvalue_v1.proto (package Ydb.KeyValue.V1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { AcquireLockRequestSchema, AcquireLockResponseSchema, AlterVolumeRequestSchema, AlterVolumeResponseSchema, CreateVolumeRequestSchema, CreateVolumeResponseSchema, DescribeVolumeRequestSchema, DescribeVolumeResponseSchema, DropVolumeRequestSchema, DropVolumeResponseSchema, ExecuteTransactionRequestSchema, ExecuteTransactionResponseSchema, GetStorageChannelStatusRequestSchema, GetStorageChannelStatusResponseSchema, ListLocalPartitionsRequestSchema, ListLocalPartitionsResponseSchema, ListRangeRequestSchema, ListRangeResponseSchema, ReadRangeRequestSchema, ReadRangeResponseSchema, ReadRequestSchema, ReadResponseSchema } from "./protos/ydb_keyvalue_pb";
import { file_draft_protos_ydb_keyvalue } from "./protos/ydb_keyvalue_pb";

/**
 * Describes the file draft/ydb_keyvalue_v1.proto.
 */
export const file_draft_ydb_keyvalue_v1: GenFile = /*@__PURE__*/
  fileDesc("ChtkcmFmdC95ZGJfa2V5dmFsdWVfdjEucHJvdG8SD1lkYi5LZXlWYWx1ZS5WMTLmBwoPS2V5VmFsdWVTZXJ2aWNlElUKDENyZWF0ZVZvbHVtZRIhLllkYi5LZXlWYWx1ZS5DcmVhdGVWb2x1bWVSZXF1ZXN0GiIuWWRiLktleVZhbHVlLkNyZWF0ZVZvbHVtZVJlc3BvbnNlEk8KCkRyb3BWb2x1bWUSHy5ZZGIuS2V5VmFsdWUuRHJvcFZvbHVtZVJlcXVlc3QaIC5ZZGIuS2V5VmFsdWUuRHJvcFZvbHVtZVJlc3BvbnNlElIKC0FsdGVyVm9sdW1lEiAuWWRiLktleVZhbHVlLkFsdGVyVm9sdW1lUmVxdWVzdBohLllkYi5LZXlWYWx1ZS5BbHRlclZvbHVtZVJlc3BvbnNlElsKDkRlc2NyaWJlVm9sdW1lEiMuWWRiLktleVZhbHVlLkRlc2NyaWJlVm9sdW1lUmVxdWVzdBokLllkYi5LZXlWYWx1ZS5EZXNjcmliZVZvbHVtZVJlc3BvbnNlEmoKE0xpc3RMb2NhbFBhcnRpdGlvbnMSKC5ZZGIuS2V5VmFsdWUuTGlzdExvY2FsUGFydGl0aW9uc1JlcXVlc3QaKS5ZZGIuS2V5VmFsdWUuTGlzdExvY2FsUGFydGl0aW9uc1Jlc3BvbnNlElIKC0FjcXVpcmVMb2NrEiAuWWRiLktleVZhbHVlLkFjcXVpcmVMb2NrUmVxdWVzdBohLllkYi5LZXlWYWx1ZS5BY3F1aXJlTG9ja1Jlc3BvbnNlEmcKEkV4ZWN1dGVUcmFuc2FjdGlvbhInLllkYi5LZXlWYWx1ZS5FeGVjdXRlVHJhbnNhY3Rpb25SZXF1ZXN0GiguWWRiLktleVZhbHVlLkV4ZWN1dGVUcmFuc2FjdGlvblJlc3BvbnNlEj0KBFJlYWQSGS5ZZGIuS2V5VmFsdWUuUmVhZFJlcXVlc3QaGi5ZZGIuS2V5VmFsdWUuUmVhZFJlc3BvbnNlEkwKCVJlYWRSYW5nZRIeLllkYi5LZXlWYWx1ZS5SZWFkUmFuZ2VSZXF1ZXN0Gh8uWWRiLktleVZhbHVlLlJlYWRSYW5nZVJlc3BvbnNlEkwKCUxpc3RSYW5nZRIeLllkYi5LZXlWYWx1ZS5MaXN0UmFuZ2VSZXF1ZXN0Gh8uWWRiLktleVZhbHVlLkxpc3RSYW5nZVJlc3BvbnNlEnYKF0dldFN0b3JhZ2VDaGFubmVsU3RhdHVzEiwuWWRiLktleVZhbHVlLkdldFN0b3JhZ2VDaGFubmVsU3RhdHVzUmVxdWVzdBotLllkYi5LZXlWYWx1ZS5HZXRTdG9yYWdlQ2hhbm5lbFN0YXR1c1Jlc3BvbnNlQl4KHXRlY2gueWRiLnByb3RvLmRyYWZ0LmtleXZhbHVlWj1naXRodWIuY29tL3lkYi1wbGF0Zm9ybS95ZGItZ28tZ2VucHJvdG8vZHJhZnQvWWRiX0tleVZhbHVlX1YxYgZwcm90bzM", [file_draft_protos_ydb_keyvalue]);

/**
 * @generated from service Ydb.KeyValue.V1.KeyValueService
 */
export const KeyValueService: GenService<{
  /**
   * Create a volume by path and partition count
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.CreateVolume
   */
  createVolume: {
    methodKind: "unary";
    input: typeof CreateVolumeRequestSchema;
    output: typeof CreateVolumeResponseSchema;
  },
  /**
   * Drop the volume by path
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.DropVolume
   */
  dropVolume: {
    methodKind: "unary";
    input: typeof DropVolumeRequestSchema;
    output: typeof DropVolumeResponseSchema;
  },
  /**
   * Alter the volume by path
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.AlterVolume
   */
  alterVolume: {
    methodKind: "unary";
    input: typeof AlterVolumeRequestSchema;
    output: typeof AlterVolumeResponseSchema;
  },
  /**
   * Describe the volume by path
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.DescribeVolume
   */
  describeVolume: {
    methodKind: "unary";
    input: typeof DescribeVolumeRequestSchema;
    output: typeof DescribeVolumeResponseSchema;
  },
  /**
   * List partitions of a volume at the local node.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.ListLocalPartitions
   */
  listLocalPartitions: {
    methodKind: "unary";
    input: typeof ListLocalPartitionsRequestSchema;
    output: typeof ListLocalPartitionsResponseSchema;
  },
  /**
   * Acquire an exclusive lock for the partition.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.AcquireLock
   */
  acquireLock: {
    methodKind: "unary";
    input: typeof AcquireLockRequestSchema;
    output: typeof AcquireLockResponseSchema;
  },
  /**
   * Perform list of commands to modify the state of the partition as an atomic transaction.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.ExecuteTransaction
   */
  executeTransaction: {
    methodKind: "unary";
    input: typeof ExecuteTransactionRequestSchema;
    output: typeof ExecuteTransactionResponseSchema;
  },
  /**
   * Read the value stored in the item with the key specified.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.Read
   */
  read: {
    methodKind: "unary";
    input: typeof ReadRequestSchema;
    output: typeof ReadResponseSchema;
  },
  /**
   * Read items with keys in the specified range.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.ReadRange
   */
  readRange: {
    methodKind: "unary";
    input: typeof ReadRangeRequestSchema;
    output: typeof ReadRangeResponseSchema;
  },
  /**
   * List keys and metadata of items with keys in the specified range.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.ListRange
   */
  listRange: {
    methodKind: "unary";
    input: typeof ListRangeRequestSchema;
    output: typeof ListRangeResponseSchema;
  },
  /**
   * Get storage channel status of the partition.
   *
   * @generated from rpc Ydb.KeyValue.V1.KeyValueService.GetStorageChannelStatus
   */
  getStorageChannelStatus: {
    methodKind: "unary";
    input: typeof GetStorageChannelStatusRequestSchema;
    output: typeof GetStorageChannelStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_draft_ydb_keyvalue_v1, 0);

