// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file draft/ydb_object_storage_v1.proto (package Ydb.ObjectStorage.V1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { ListingRequestSchema, ListingResponseSchema } from "./protos/ydb_object_storage_pb";
import { file_draft_protos_ydb_object_storage } from "./protos/ydb_object_storage_pb";

/**
 * Describes the file draft/ydb_object_storage_v1.proto.
 */
export const file_draft_ydb_object_storage_v1: GenFile = /*@__PURE__*/
  fileDesc("CiFkcmFmdC95ZGJfb2JqZWN0X3N0b3JhZ2VfdjEucHJvdG8SFFlkYi5PYmplY3RTdG9yYWdlLlYxMmUKFE9iamVjdFN0b3JhZ2VTZXJ2aWNlEk0KBExpc3QSIS5ZZGIuT2JqZWN0U3RvcmFnZS5MaXN0aW5nUmVxdWVzdBoiLllkYi5PYmplY3RTdG9yYWdlLkxpc3RpbmdSZXNwb25zZUJsCiZ0ZWNoLnlkYi5wcm90by5kcmFmdC5vYmplY3Rfc3RvcmFnZS52MVpCZ2l0aHViLmNvbS95ZGItcGxhdGZvcm0veWRiLWdvLWdlbnByb3RvL2RyYWZ0L1lkYl9PYmplY3RTdG9yYWdlX1YxYgZwcm90bzM", [file_draft_protos_ydb_object_storage]);

/**
 * @generated from service Ydb.ObjectStorage.V1.ObjectStorageService
 */
export const ObjectStorageService: GenService<{
  /**
   * @generated from rpc Ydb.ObjectStorage.V1.ObjectStorageService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListingRequestSchema;
    output: typeof ListingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_draft_ydb_object_storage_v1, 0);

