// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file draft/ydb_dynamic_config_v1.proto (package Ydb.DynamicConfig.V1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { AddVolatileConfigRequestSchema, AddVolatileConfigResponseSchema, DropConfigRequestSchema, DropConfigResponseSchema, GetConfigRequestSchema, GetConfigResponseSchema, GetMetadataRequestSchema, GetMetadataResponseSchema, GetNodeLabelsRequestSchema, GetNodeLabelsResponseSchema, RemoveVolatileConfigRequestSchema, RemoveVolatileConfigResponseSchema, ReplaceConfigRequestSchema, ReplaceConfigResponseSchema, ResolveAllConfigRequestSchema, ResolveAllConfigResponseSchema, ResolveConfigRequestSchema, ResolveConfigResponseSchema, SetConfigRequestSchema, SetConfigResponseSchema } from "./protos/ydb_dynamic_config_pb";
import { file_draft_protos_ydb_dynamic_config } from "./protos/ydb_dynamic_config_pb";

/**
 * Describes the file draft/ydb_dynamic_config_v1.proto.
 */
export const file_draft_ydb_dynamic_config_v1: GenFile = /*@__PURE__*/
  fileDesc("CiFkcmFmdC95ZGJfZHluYW1pY19jb25maWdfdjEucHJvdG8SFFlkYi5EeW5hbWljQ29uZmlnLlYxMoEIChREeW5hbWljQ29uZmlnU2VydmljZRJWCglTZXRDb25maWcSIy5ZZGIuRHluYW1pY0NvbmZpZy5TZXRDb25maWdSZXF1ZXN0GiQuWWRiLkR5bmFtaWNDb25maWcuU2V0Q29uZmlnUmVzcG9uc2USYgoNUmVwbGFjZUNvbmZpZxInLllkYi5EeW5hbWljQ29uZmlnLlJlcGxhY2VDb25maWdSZXF1ZXN0GiguWWRiLkR5bmFtaWNDb25maWcuUmVwbGFjZUNvbmZpZ1Jlc3BvbnNlElwKC0dldE1ldGFkYXRhEiUuWWRiLkR5bmFtaWNDb25maWcuR2V0TWV0YWRhdGFSZXF1ZXN0GiYuWWRiLkR5bmFtaWNDb25maWcuR2V0TWV0YWRhdGFSZXNwb25zZRJWCglHZXRDb25maWcSIy5ZZGIuRHluYW1pY0NvbmZpZy5HZXRDb25maWdSZXF1ZXN0GiQuWWRiLkR5bmFtaWNDb25maWcuR2V0Q29uZmlnUmVzcG9uc2USWQoKRHJvcENvbmZpZxIkLllkYi5EeW5hbWljQ29uZmlnLkRyb3BDb25maWdSZXF1ZXN0GiUuWWRiLkR5bmFtaWNDb25maWcuRHJvcENvbmZpZ1Jlc3BvbnNlEm4KEUFkZFZvbGF0aWxlQ29uZmlnEisuWWRiLkR5bmFtaWNDb25maWcuQWRkVm9sYXRpbGVDb25maWdSZXF1ZXN0GiwuWWRiLkR5bmFtaWNDb25maWcuQWRkVm9sYXRpbGVDb25maWdSZXNwb25zZRJ3ChRSZW1vdmVWb2xhdGlsZUNvbmZpZxIuLllkYi5EeW5hbWljQ29uZmlnLlJlbW92ZVZvbGF0aWxlQ29uZmlnUmVxdWVzdBovLllkYi5EeW5hbWljQ29uZmlnLlJlbW92ZVZvbGF0aWxlQ29uZmlnUmVzcG9uc2USYgoNR2V0Tm9kZUxhYmVscxInLllkYi5EeW5hbWljQ29uZmlnLkdldE5vZGVMYWJlbHNSZXF1ZXN0GiguWWRiLkR5bmFtaWNDb25maWcuR2V0Tm9kZUxhYmVsc1Jlc3BvbnNlEmIKDVJlc29sdmVDb25maWcSJy5ZZGIuRHluYW1pY0NvbmZpZy5SZXNvbHZlQ29uZmlnUmVxdWVzdBooLllkYi5EeW5hbWljQ29uZmlnLlJlc29sdmVDb25maWdSZXNwb25zZRJrChBSZXNvbHZlQWxsQ29uZmlnEiouWWRiLkR5bmFtaWNDb25maWcuUmVzb2x2ZUFsbENvbmZpZ1JlcXVlc3QaKy5ZZGIuRHluYW1pY0NvbmZpZy5SZXNvbHZlQWxsQ29uZmlnUmVzcG9uc2VCbgoldGVjaC55ZGIucHJvdG8uZHJhZnQuZHluYW1pY2NvbmZpZy52MVpCZ2l0aHViLmNvbS95ZGItcGxhdGZvcm0veWRiLWdvLWdlbnByb3RvL2RyYWZ0L1lkYl9EeW5hbWljQ29uZmlnX1Yx+AEBYgZwcm90bzM", [file_draft_protos_ydb_dynamic_config]);

/**
 * @generated from service Ydb.DynamicConfig.V1.DynamicConfigService
 */
export const DynamicConfigService: GenService<{
  /**
   * Apply new version of config.
   * Overwrites previous version.
   * This call is idempotent:
   *  - Two subsequent identical calls will return success,
   *  - After applying next version another identical call will result in an error.
   * The field version within the YAML in the request must strictly be set to the current version increment by one.
   * The field cluster within the YAML should be identical to the one configured on the node used by the console tablet.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.SetConfig
   */
  setConfig: {
    methodKind: "unary";
    input: typeof SetConfigRequestSchema;
    output: typeof SetConfigResponseSchema;
  },
  /**
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.ReplaceConfig
   */
  replaceConfig: {
    methodKind: "unary";
    input: typeof ReplaceConfigRequestSchema;
    output: typeof ReplaceConfigResponseSchema;
  },
  /**
   * Get current configs metadata.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.GetMetadata
   */
  getMetadata: {
    methodKind: "unary";
    input: typeof GetMetadataRequestSchema;
    output: typeof GetMetadataResponseSchema;
  },
  /**
   * Get current configs.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.GetConfig
   */
  getConfig: {
    methodKind: "unary";
    input: typeof GetConfigRequestSchema;
    output: typeof GetConfigResponseSchema;
  },
  /**
   * Drop current config.
   * This call is idempotent.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.DropConfig
   */
  dropConfig: {
    methodKind: "unary";
    input: typeof DropConfigRequestSchema;
    output: typeof DropConfigResponseSchema;
  },
  /**
   * Add volatile config.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.AddVolatileConfig
   */
  addVolatileConfig: {
    methodKind: "unary";
    input: typeof AddVolatileConfigRequestSchema;
    output: typeof AddVolatileConfigResponseSchema;
  },
  /**
   * Remove volatile config.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.RemoveVolatileConfig
   */
  removeVolatileConfig: {
    methodKind: "unary";
    input: typeof RemoveVolatileConfigRequestSchema;
    output: typeof RemoveVolatileConfigResponseSchema;
  },
  /**
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.GetNodeLabels
   */
  getNodeLabels: {
    methodKind: "unary";
    input: typeof GetNodeLabelsRequestSchema;
    output: typeof GetNodeLabelsResponseSchema;
  },
  /**
   * Resolve config for particular labels.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.ResolveConfig
   */
  resolveConfig: {
    methodKind: "unary";
    input: typeof ResolveConfigRequestSchema;
    output: typeof ResolveConfigResponseSchema;
  },
  /**
   * Resolve config for all possible labels combinations.
   *
   * @generated from rpc Ydb.DynamicConfig.V1.DynamicConfigService.ResolveAllConfig
   */
  resolveAllConfig: {
    methodKind: "unary";
    input: typeof ResolveAllConfigRequestSchema;
    output: typeof ResolveAllConfigResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_draft_ydb_dynamic_config_v1, 0);

