// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file draft/ydb_maintenance_v1.proto (package Ydb.Maintenance.V1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CompleteActionRequestSchema, CreateMaintenanceTaskRequestSchema, DropMaintenanceTaskRequestSchema, GetMaintenanceTaskRequestSchema, GetMaintenanceTaskResponseSchema, ListClusterNodesRequestSchema, ListClusterNodesResponseSchema, ListMaintenanceTasksRequestSchema, ListMaintenanceTasksResponseSchema, MaintenanceTaskResponseSchema, ManageActionResponseSchema, ManageMaintenanceTaskResponseSchema, RefreshMaintenanceTaskRequestSchema } from "./protos/ydb_maintenance_pb";
import { file_draft_protos_ydb_maintenance } from "./protos/ydb_maintenance_pb";

/**
 * Describes the file draft/ydb_maintenance_v1.proto.
 */
export const file_draft_ydb_maintenance_v1: GenFile = /*@__PURE__*/
  fileDesc("Ch5kcmFmdC95ZGJfbWFpbnRlbmFuY2VfdjEucHJvdG8SEllkYi5NYWludGVuYW5jZS5WMTKcBgoSTWFpbnRlbmFuY2VTZXJ2aWNlEmcKEExpc3RDbHVzdGVyTm9kZXMSKC5ZZGIuTWFpbnRlbmFuY2UuTGlzdENsdXN0ZXJOb2Rlc1JlcXVlc3QaKS5ZZGIuTWFpbnRlbmFuY2UuTGlzdENsdXN0ZXJOb2Rlc1Jlc3BvbnNlEnAKFUNyZWF0ZU1haW50ZW5hbmNlVGFzaxItLllkYi5NYWludGVuYW5jZS5DcmVhdGVNYWludGVuYW5jZVRhc2tSZXF1ZXN0GiguWWRiLk1haW50ZW5hbmNlLk1haW50ZW5hbmNlVGFza1Jlc3BvbnNlEnIKFlJlZnJlc2hNYWludGVuYW5jZVRhc2sSLi5ZZGIuTWFpbnRlbmFuY2UuUmVmcmVzaE1haW50ZW5hbmNlVGFza1JlcXVlc3QaKC5ZZGIuTWFpbnRlbmFuY2UuTWFpbnRlbmFuY2VUYXNrUmVzcG9uc2USbQoSR2V0TWFpbnRlbmFuY2VUYXNrEiouWWRiLk1haW50ZW5hbmNlLkdldE1haW50ZW5hbmNlVGFza1JlcXVlc3QaKy5ZZGIuTWFpbnRlbmFuY2UuR2V0TWFpbnRlbmFuY2VUYXNrUmVzcG9uc2UScwoUTGlzdE1haW50ZW5hbmNlVGFza3MSLC5ZZGIuTWFpbnRlbmFuY2UuTGlzdE1haW50ZW5hbmNlVGFza3NSZXF1ZXN0Gi0uWWRiLk1haW50ZW5hbmNlLkxpc3RNYWludGVuYW5jZVRhc2tzUmVzcG9uc2UScgoTRHJvcE1haW50ZW5hbmNlVGFzaxIrLllkYi5NYWludGVuYW5jZS5Ecm9wTWFpbnRlbmFuY2VUYXNrUmVxdWVzdBouLllkYi5NYWludGVuYW5jZS5NYW5hZ2VNYWludGVuYW5jZVRhc2tSZXNwb25zZRJfCg5Db21wbGV0ZUFjdGlvbhImLllkYi5NYWludGVuYW5jZS5Db21wbGV0ZUFjdGlvblJlcXVlc3QaJS5ZZGIuTWFpbnRlbmFuY2UuTWFuYWdlQWN0aW9uUmVzcG9uc2VCZAogdGVjaC55ZGIucHJvdG8uZHJhZnQubWFpbnRlbmFuY2VaQGdpdGh1Yi5jb20veWRiLXBsYXRmb3JtL3lkYi1nby1nZW5wcm90by9kcmFmdC9ZZGJfTWFpbnRlbmFuY2VfVjFiBnByb3RvMw", [file_draft_protos_ydb_maintenance]);

/**
 * @generated from service Ydb.Maintenance.V1.MaintenanceService
 */
export const MaintenanceService: GenService<{
  /**
   * List cluster nodes.
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.ListClusterNodes
   */
  listClusterNodes: {
    methodKind: "unary";
    input: typeof ListClusterNodesRequestSchema;
    output: typeof ListClusterNodesResponseSchema;
  },
  /**
   * Create maintenance task.
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.CreateMaintenanceTask
   */
  createMaintenanceTask: {
    methodKind: "unary";
    input: typeof CreateMaintenanceTaskRequestSchema;
    output: typeof MaintenanceTaskResponseSchema;
  },
  /**
   * Try to perform maintenance task's actions (polling).
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.RefreshMaintenanceTask
   */
  refreshMaintenanceTask: {
    methodKind: "unary";
    input: typeof RefreshMaintenanceTaskRequestSchema;
    output: typeof MaintenanceTaskResponseSchema;
  },
  /**
   * Get detailed task information.
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.GetMaintenanceTask
   */
  getMaintenanceTask: {
    methodKind: "unary";
    input: typeof GetMaintenanceTaskRequestSchema;
    output: typeof GetMaintenanceTaskResponseSchema;
  },
  /**
   * List maintenance tasks.
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.ListMaintenanceTasks
   */
  listMaintenanceTasks: {
    methodKind: "unary";
    input: typeof ListMaintenanceTasksRequestSchema;
    output: typeof ListMaintenanceTasksResponseSchema;
  },
  /**
   * Drop maintenance task.
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.DropMaintenanceTask
   */
  dropMaintenanceTask: {
    methodKind: "unary";
    input: typeof DropMaintenanceTaskRequestSchema;
    output: typeof ManageMaintenanceTaskResponseSchema;
  },
  /**
   * Mark action as completed.
   *
   * @generated from rpc Ydb.Maintenance.V1.MaintenanceService.CompleteAction
   */
  completeAction: {
    methodKind: "unary";
    input: typeof CompleteActionRequestSchema;
    output: typeof ManageActionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_draft_ydb_maintenance_v1, 0);

