// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file draft/protos/ydb_object_storage.proto (package Ydb.ObjectStorage, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { IssueMessage } from "../../protos/ydb_issue_message_pb";
import { file_protos_ydb_issue_message } from "../../protos/ydb_issue_message_pb";
import type { ResultSet, TypedValue } from "../../protos/ydb_value_pb";
import { file_protos_ydb_value } from "../../protos/ydb_value_pb";
import type { StatusIds_StatusCode } from "../../protos/ydb_status_codes_pb";
import { file_protos_ydb_status_codes } from "../../protos/ydb_status_codes_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file draft/protos/ydb_object_storage.proto.
 */
export const file_draft_protos_ydb_object_storage: GenFile = /*@__PURE__*/
  fileDesc("CiVkcmFmdC9wcm90b3MveWRiX29iamVjdF9zdG9yYWdlLnByb3RvEhFZZGIuT2JqZWN0U3RvcmFnZSLWAgoOTGlzdGluZ1JlcXVlc3QSEgoKdGFibGVfbmFtZRgBIAEoCRIjCgprZXlfcHJlZml4GAIgASgLMg8uWWRiLlR5cGVkVmFsdWUSGgoScGF0aF9jb2x1bW5fcHJlZml4GAMgASgJEh0KFXBhdGhfY29sdW1uX2RlbGltaXRlchgEIAEoCRIaChJjb250aW51YXRpb25fdG9rZW4YBSABKAwSLwoWc3RhcnRfYWZ0ZXJfa2V5X3N1ZmZpeBgGIAEoCzIPLllkYi5UeXBlZFZhbHVlEhAKCG1heF9rZXlzGAcgASgFEhkKEWNvbHVtbnNfdG9fcmV0dXJuGAggAygJEigKD21hdGNoaW5nX2ZpbHRlchgKIAEoCzIPLllkYi5UeXBlZFZhbHVlIiYKCkVNYXRjaFR5cGUSCQoFRVFVQUwQABINCglOT1RfRVFVQUwQAUoECAkQCiLXAQoPTGlzdGluZ1Jlc3BvbnNlEikKBnN0YXR1cxgBIAEoDjIZLllkYi5TdGF0dXNJZHMuU3RhdHVzQ29kZRInCgZpc3N1ZXMYAiADKAsyFy5ZZGIuSXNzdWUuSXNzdWVNZXNzYWdlEhcKD2NvbW1vbl9wcmVmaXhlcxgDIAMoCRIgCghjb250ZW50cxgEIAEoCzIOLllkYi5SZXN1bHRTZXQSFAoMaXNfdHJ1bmNhdGVkGAUgASgIEh8KF25leHRfY29udGludWF0aW9uX3Rva2VuGAYgASgMQnAKI3RlY2gueWRiLnByb3RvLmRyYWZ0Lm9iamVjdF9zdG9yYWdlWkZnaXRodWIuY29tL3lkYi1wbGF0Zm9ybS95ZGItZ28tZ2VucHJvdG8vZHJhZnQvcHJvdG9zL1lkYl9PYmplY3RTdG9yYWdl+AEBYgZwcm90bzM", [file_protos_ydb_issue_message, file_protos_ydb_value, file_protos_ydb_status_codes]);

/**
 * @generated from message Ydb.ObjectStorage.ListingRequest
 */
export type ListingRequest = Message<"Ydb.ObjectStorage.ListingRequest"> & {
  /**
   * @generated from field: string table_name = 1;
   */
  tableName: string;

  /**
   * A tuple representing all key columns that preceed path column
   *
   * @generated from field: Ydb.TypedValue key_prefix = 2;
   */
  keyPrefix?: TypedValue;

  /**
   * @generated from field: string path_column_prefix = 3;
   */
  pathColumnPrefix: string;

  /**
   * @generated from field: string path_column_delimiter = 4;
   */
  pathColumnDelimiter: string;

  /**
   * @generated from field: bytes continuation_token = 5;
   */
  continuationToken: Uint8Array;

  /**
   * A tuple representing key columns that succeed path column
   *
   * @generated from field: Ydb.TypedValue start_after_key_suffix = 6;
   */
  startAfterKeySuffix?: TypedValue;

  /**
   * @generated from field: int32 max_keys = 7;
   */
  maxKeys: number;

  /**
   * @generated from field: repeated string columns_to_return = 8;
   */
  columnsToReturn: string[];

  /**
   * @generated from field: Ydb.TypedValue matching_filter = 10;
   */
  matchingFilter?: TypedValue;
};

/**
 * Describes the message Ydb.ObjectStorage.ListingRequest.
 * Use `create(ListingRequestSchema)` to create a new message.
 */
export const ListingRequestSchema: GenMessage<ListingRequest> = /*@__PURE__*/
  messageDesc(file_draft_protos_ydb_object_storage, 0);

/**
 * @generated from enum Ydb.ObjectStorage.ListingRequest.EMatchType
 */
export enum ListingRequest_EMatchType {
  /**
   * @generated from enum value: EQUAL = 0;
   */
  EQUAL = 0,

  /**
   * @generated from enum value: NOT_EQUAL = 1;
   */
  NOT_EQUAL = 1,
}

/**
 * Describes the enum Ydb.ObjectStorage.ListingRequest.EMatchType.
 */
export const ListingRequest_EMatchTypeSchema: GenEnum<ListingRequest_EMatchType> = /*@__PURE__*/
  enumDesc(file_draft_protos_ydb_object_storage, 0, 0);

/**
 * @generated from message Ydb.ObjectStorage.ListingResponse
 */
export type ListingResponse = Message<"Ydb.ObjectStorage.ListingResponse"> & {
  /**
   * @generated from field: Ydb.StatusIds.StatusCode status = 1;
   */
  status: StatusIds_StatusCode;

  /**
   * @generated from field: repeated Ydb.Issue.IssueMessage issues = 2;
   */
  issues: IssueMessage[];

  /**
   * Folders.
   *
   * @generated from field: repeated string common_prefixes = 3;
   */
  commonPrefixes: string[];

  /**
   * Every Contents row starts with key suffix with KeySuffixSize columns
   *
   * @generated from field: Ydb.ResultSet contents = 4;
   */
  contents?: ResultSet;

  /**
   * @generated from field: bool is_truncated = 5;
   */
  isTruncated: boolean;

  /**
   * @generated from field: bytes next_continuation_token = 6;
   */
  nextContinuationToken: Uint8Array;
};

/**
 * Describes the message Ydb.ObjectStorage.ListingResponse.
 * Use `create(ListingResponseSchema)` to create a new message.
 */
export const ListingResponseSchema: GenMessage<ListingResponse> = /*@__PURE__*/
  messageDesc(file_draft_protos_ydb_object_storage, 1);

